import Head from 'next/head'
import Header from '../components/Shop/Header'
import Hero from '../components/Shop/Hero'

const shop = () => {
  return (
    <div>
        <Head>
            <title>Printico | Shop</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <Hero />
    </div>
  )
}

export default shop